workflows:
  environment:
    vars:
      GH_USER: madispp
      GH_PAT: Encrypted(Z0FBQUFBQmQxbXVQeE5qUmlHeHhCVGZxMkJDTUFRZmZ3bFhubG9rWjNBR1ZYbDJWWk5lbTN5VWxOaElQN1hJbk1iVjdUYjV0elpTUHJlN1JzWHMxUWY0dzBrNXk1ZGpiZmw4UEZDQ1NYazRaVDZRRHotUUlGSXRtbGRjN292TDJpcUFLbkItSzdaajI=)
      # GH_PAT: Encrypted(Z0FBQUFBQmQxbWhBNVc0WmZjQUQ0d1VYbF8xdW9UakJSc25YbFVsN2RQUUx6SGZ1aFdpMHR4NWNFVU52UGlQT3lsb3h3SUFkUG83eWFCMjlxbTBfaXQ4M0U1UEtKODFmX3RNakxNRHJ2Q1JaQXJKaUlLX0pucmJDS3J4ZTVLOU1ZdmNtMjE3OElMX3Y=)
      REPOSITORY: codemagic-ci-cd/cli-tools
  release:
    name: Generate binary distribution wheel
    scripts:
      - git tag -a v$(python3 setup.py --version)
      - python3 setup.py bdist_wheel
      - git push "https://$GH_USER:$GH_PAT@github.com/$REPOSITORY" -tags
      - echo "Initial release\n" > release_notes.txt
      - |
        # draft a release
        TAG_NAME=v$(python3 setup.py --version)
        RELEASE_NOTES=$(cat release_notes.txt)
        PAYLOAD=$(cat <<"EOF"
          {
            "tag_name": $TAG_NAME,
            "name": $TAG_NAME,
            "body": $RELEASE_NOTES,
            "draft": true,
            "prerelease": true
          }
        EOF
        )
        RELEASE=$(curl -u $GH_USER:$GH_PAT --silent -H 'Content-Type: application/json' -X POST --data $PAYLOAD "https://api.github.com/repos/${REPOSITORY}/releases?access_token=${GH_PAT}")
    artifacts:
      - dist/codemagic-*.whl
