workflows:
  release:
    environment:
      vars:
        GH_USER: madispp
        GH_PAT: Encrypted(Z0FBQUFBQmQxcFUxdDNKMVNkOGdENlZrdVdKUkxwaTdlWVNPQU56LTczVjFoZk1xalVTVlh1YzhLRFotaGFIemF4NkdYN3BicHdRcmxJcmZhbG5rb1lTelFsUXZCY0ZUN0U3ZW4zTEoyN0FqX2wxUUZKdV9LVTJPLVF5aXpzekMzOWUyTkNIX3Vpam8=)
        REPOSITORY: codemagic-ci-cd/cli-tools
    name: Generate binary distribution wheel
    scripts:
      - git tag -a v$(python3 setup.py --version) -m "Release v$(python3 setup.py --version)"
      - python3 setup.py bdist_wheel
      - git push "https://$GH_USER:$GH_PAT@github.com/$REPOSITORY" --tags
      - |
        # create release notes
        previous_version_line=$(grep -n "^Version " CHANGELOG.md | head -2 | tail -1 | cut -f1 -d:)
        head -n "$(($previous_version_line - 1))" CHANGELOG.md | tail +3 > release_notes.txt
      - |
        # draft a release
        set -e

        TAG_NAME=v$(python3 setup.py --version)
        RELEASE_NOTES=$(cat release_notes.txt)
        PAYLOAD="{\"tag_name\":\"$TAG_NAME\",\"name\":\"$TAG_NAME\",\"body\":\"$RELEASE_NOTES\",\"draft\":true,\"prerelease\":true}"
        RELEASE=$(curl -u "$GH_USER":"$GH_PAT" --silent --fail -H 'Content-Type: application/json' -X POST --data "$PAYLOAD" "https://api.github.com/repos/${REPOSITORY}/releases")
        EDIT_URL=$(echo $RELEASE | python -c 'import sys, json; print json.load(sys.stdin).get("html_url").replace("/tag/", "/edit/")')
        FILE_NAME=$(cd dist && ls *.whl | tail -n1)
        UPLOAD_URL=$(echo $RELEASE | python -c "import sys, json; print json.load(sys.stdin).get('upload_url').replace('{?name,label}', '?name=$FILE_NAME')")
        curl -u "$GH_USER":"$GH_PAT" --silent --fail -H 'Content-Type: application/x-wheel+zip' -X POST "$UPLOAD_URL" --data-binary "@dist/$FILE_NAME" > /dev/null
        echo "Draft release created. Finalize it at $EDIT_URL"
    artifacts:
      - dist/codemagic-*.whl
