name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with:
        path: /home/runner/.local/share/virtualenvs/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev
    - name: Static type checks with mypy
      run: |
        export MYPYPATH=stubs
        python -m mypy src/codemagic_cli_tools
    - name: Test with pytest
      run: |
        python -m pytest
