name: Checks

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v1
      with:
        path: /home/runner/.local/share/virtualenvs/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev

    - name: Pipenv checks
      run: |
        pipenv checks

#     - name: Static type checks with mypy
#       run: |
#         export MYPYPATH=stubs
#         pipenv run mypy src/codemagic_cli_tools
# 
    - name: Test with pytest
      run: |
        pipenv run pytest
